export const filterConditionsBooleanYaml = `apply_to: field_path
conditions:         ### PostgreSQL ###
- f\`\`               # true // the same as no filter

- f\`true\`           # AND ...
- f\`=false\`         # AND ...
- f\`false\`          # AND ...
- f\`null\`           # AND ...
- f\`not null\`       # AND ...`

